[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-dead_strip"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-dead_strip"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"